"""CO-GRID backend — FastAPI serving processed GeoJSON/JSON artifacts.

Run:  ./venv/bin/uvicorn src.api.main:app --host 127.0.0.1 --port 8000 --reload
Data: everything under data/processed/ (generated by src/processing/*).
"""
from __future__ import annotations

import csv
import io
import json
import os
from functools import lru_cache
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from fastapi.middleware.gzip import GZipMiddleware
from fastapi.responses import FileResponse

load_dotenv()

ROOT = Path(__file__).resolve().parents[2]
PROCESSED = ROOT / "data" / "processed"
RAW = ROOT / "data" / "raw"

app = FastAPI(title="CO-GRID API", version="0.1.0")
app.add_middleware(
    CORSMiddleware,
    allow_origins=[os.getenv("CORS_ORIGIN", "http://127.0.0.1:3210"), "http://localhost:3210"],
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)
# ~27 MB city scenes -> ~5 MB on the wire; huge win for first paint.
app.add_middleware(GZipMiddleware, minimum_size=20_000)

# AI coordination analyst (OpenAI-compatible backend, key stays server-side)
from src.agent.routes import router as agent_router  # noqa: E402
app.include_router(agent_router)

# Deterministic analysis layer — timeline bands, impact/cost estimates
from src.analysis.routes import router as analysis_router  # noqa: E402
app.include_router(analysis_router)


def _load(name: str) -> dict:
    path = PROCESSED / name
    if not path.exists():
        raise HTTPException(503, f"{name} not generated yet — run the processing pipeline")
    return json.loads(path.read_text())


@lru_cache(maxsize=8)
def _cached(name: str, mtime: float) -> dict:  # noqa: ARG001 — mtime busts cache
    return _load(name)


def _fresh(name: str) -> dict:
    path = PROCESSED / name
    return _cached(name, path.stat().st_mtime if path.exists() else 0.0)


@app.get("/api/health")
def health() -> dict:
    return {"ok": True, "processed": sorted(p.name for p in PROCESSED.glob("*"))}


@app.get("/api/meta")
def meta() -> dict:
    """Artifact freshness — when each processed file was built and its size.
    Lets the UI show 'data generated <ts>' honestly."""
    import datetime as _dt
    files = {}
    for p in sorted(PROCESSED.glob("*")):
        st = p.stat()
        files[p.name] = {
            "bytes": st.st_size,
            "built_utc": _dt.datetime.fromtimestamp(
                st.st_mtime, tz=_dt.timezone.utc).isoformat(timespec="seconds"),
        }
    return {"processed": files,
            "raw_files": sum(1 for p in RAW.glob("**/*") if p.is_file()) if RAW.exists() else 0}


@app.get("/api/projects")
def projects(
    utility: Optional[str] = Query(None),
    zone: Optional[str] = Query(None),
    q: Optional[str] = Query(None, description="substring match on id, name, utility, source"),
) -> dict:
    fc = _fresh("projects.geojson")
    feats = fc.get("features", [])
    if utility:
        feats = [f for f in feats if f["properties"].get("utility") == utility]
    if zone:
        feats = [f for f in feats if zone in f["properties"].get("zones", [zone])]
    if q:
        needle = q.strip().lower()
        feats = [f for f in feats if needle in json.dumps(
            f.get("properties", {})).lower()]
    return {**fc, "features": feats}


@app.get("/api/basemap")
def basemap(zone: Optional[str] = Query(None)) -> dict:  # noqa: ARG001
    return _fresh("basemap.geojson")


@app.get("/api/city/{scene}")
def city(scene: str) -> dict:
    if scene not in ("savannah", "augusta", "state"):
        raise HTTPException(404, "unknown scene")
    return _fresh(f"city_{scene}.json")


@app.get("/api/regions")
def regions() -> dict:
    """Index of renderable regions/scenes — the contract for statewide tiles.
    Each entry: id, label, lon/lat bounds, center, and which artifacts exist.
    The frontend can offer scene switching/tiles off this list without
    hardcoding geography."""
    out = []
    for scene, label, bounds, center in [
        ("savannah", "Savannah corridor",
         [-81.42, 31.98, -80.78, 32.55], [-81.1, 32.13]),
        ("augusta", "Augusta corridor",
         [-82.35, 33.25, -81.60, 33.68], [-81.97, 33.45]),
    ]:
        p = PROCESSED / f"city_{scene}.json"
        out.append({
            "id": scene,
            "label": label,
            "bounds": bounds,
            "center": center,
            "artifact": f"city_{scene}.json",
            "built": p.exists(),
            "size_mb": round(p.stat().st_size / 1e6, 1) if p.exists() else None,
        })
    # Statewide entry — basemap.geojson now covers GA+SC (~15.7k features);
    # the city_<state>.json scene lands separately (tiles, not one payload).
    bm = PROCESSED / "basemap.geojson"
    out.append({
        "id": "state",
        "label": "Georgia + South Carolina (statewide)",
        "bounds": [-85.65, 30.35, -78.50, 35.25],
        "center": [-82.0, 32.8],
        "artifact": "basemap.geojson",
        "built": bm.exists(),
        "size_mb": round(bm.stat().st_size / 1e6, 1) if bm.exists() else None,
        "city_scene": (PROCESSED / "city_state.json").exists(),
        "coverage": "existing grid statewide; planned projects corridor-focused",
    })
    # zone rollup — region tags carried by the data itself (projects.zones
    # and the derived overlap.zone labels) so a picker can scope by region.
    projs = _fresh("projects.geojson").get("features", [])
    ovs = _fresh("overlaps.json").get("overlaps", [])
    zones: dict[str, dict] = {}
    for f in projs:
        for z in f["properties"].get("zones") or []:
            zones.setdefault(z, {"id": z, "projects": 0, "overlaps": 0})
            zones[z]["projects"] += 1
    for o in ovs:
        for z in (o.get("zone") or "").split(" / "):
            if z in zones:
                zones[z]["overlaps"] += 1
    return {"regions": out, "zones": sorted(zones.values(), key=lambda z: -z["overlaps"])}


_OVERLAP_SORTS = {
    "score": lambda r: (-r.get("score", 0)),
    "distance": lambda r: (r.get("min_distance_km") or 1e9, -r.get("score", 0)),
    "year": lambda r: (
        (r.get("shared_window") or {}).get("start") or 9999,
        -r.get("score", 0)),
}


@app.get("/api/overlaps")
def overlaps(
    tier: Optional[int] = Query(None, ge=1, le=4),
    timeline_only: bool = Query(False),
    q: Optional[str] = Query(None, description="substring match on ids, project names, utilities"),
    zone: Optional[str] = Query(None, description="region tag — matches zone labels incl. 'a / b' pairs"),
    sort: Optional[str] = Query(None, description="score | distance | year"),
    limit: Optional[int] = Query(None, ge=1, le=500),
) -> dict:
    data = _fresh("overlaps.json")
    rows = data.get("overlaps", [])
    if tier is not None:
        rows = [r for r in rows if r["tier"] == tier]
    if zone:
        z = zone.strip().lower()
        rows = [r for r in rows if z in (r.get("zone") or "").lower()]
    if timeline_only:
        rows = [r for r in rows if r["timeline_overlap"]]
    if q:
        needle = q.strip().lower()
        rows = [r for r in rows if needle in json.dumps({
            "id": r.get("overlap_id"), "a": r.get("project_a"),
            "b": r.get("project_b"), "u": r.get("utilities"),
            "x": r.get("explanation"),
        }).lower()]
    if sort is not None:
        if sort not in _OVERLAP_SORTS:
            raise HTTPException(422, f"unknown sort {sort!r} — use score|distance|year")
        rows = sorted(rows, key=_OVERLAP_SORTS[sort])
    if limit is not None:
        rows = rows[:limit]
    return {**data, "overlaps": rows}


@app.get("/api/overlaps.csv")
def overlaps_csv(
    tier: Optional[int] = Query(None, ge=1, le=4),
    timeline_only: bool = Query(False),
) -> "Response":
    """Ranked overlaps as flat CSV — teammates/spreadsheets/BI friendly."""
    from fastapi.responses import Response

    rows = _fresh("overlaps.json").get("overlaps", [])
    if tier is not None:
        rows = [r for r in rows if r["tier"] == tier]
    if timeline_only:
        rows = [r for r in rows if r["timeline_overlap"]]
    rows = sorted(rows, key=lambda r: r.get("score", 0), reverse=True)

    cols = [
        "rank", "overlap_id", "project_a", "project_b", "utilities",
        "tier", "tier_label", "zone", "min_distance_km", "timeline_overlap",
        "shared_window_start", "shared_window_end",
        "closest_lon", "closest_lat", "score",
        "shared_row_km", "est_savings_low_usd", "est_savings_high_usd",
        "explanation",
    ]
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(cols)
    for i, r in enumerate(rows, 1):
        win = r.get("shared_window") or {}
        cp = r.get("closest_point_a") or [None, None]
        cost = r.get("cost") or {}
        w.writerow([
            i, r.get("overlap_id"), r.get("project_a"), r.get("project_b"),
            "|".join(r.get("utilities") or []), r.get("tier"), r.get("tier_label"),
            r.get("zone"), r.get("min_distance_km"), r.get("timeline_overlap"),
            win.get("start"), win.get("end"), cp[0], cp[1], r.get("score"),
            cost.get("shared_row_km"), cost.get("est_savings_usd_low"),
            cost.get("est_savings_usd_high"), r.get("explanation"),
        ])
    return Response(
        content=buf.getvalue(),
        media_type="text/csv",
        headers={"Content-Disposition": 'attachment; filename="co-grid-overlaps.csv"'},
    )


@app.get("/api/stats")
def stats() -> dict:
    projs = _fresh("projects.geojson").get("features", [])
    ovs = _fresh("overlaps.json").get("overlaps", [])
    by_util: dict[str, int] = {}
    by_tier: dict[str, int] = {}
    for f in projs:
        u = f["properties"].get("utility", "?")
        by_util[u] = by_util.get(u, 0) + 1
    for o in ovs:
        t = str(o["tier"])
        by_tier[t] = by_tier.get(t, 0) + 1
    out = {
        "projects": len(projs),
        "by_utility": by_util,
        "overlaps": len(ovs),
        "by_tier": by_tier,
        "timeline_matches": sum(1 for o in ovs if o["timeline_overlap"]),
    }
    # program-level rollup — staging regions + busiest shared season
    try:
        from src.analysis.clusters import build_clusters
        from src.analysis.optimize import build_playbook
        cl = build_clusters({"overlaps": ovs}, 40.0)
        pb = build_playbook({"overlaps": ovs}, 40.0, 5)
        seasons = [s for c in pb.get("clusters", []) for s in c.get("seasons", [])]
        out["staging_regions"] = cl.get("cluster_count", 0)
        out["peak_season"] = max(seasons, key=lambda s: s["site_count"], default=None)
    except Exception:
        out["staging_regions"] = None
        out["peak_season"] = None
    # per-utility coverage: filed projects participating in >=1 overlap
    proj_ids = {
        f["properties"].get("project_id"): f["properties"].get("utility", "?")
        for f in projs
    }
    covered: dict[str, set] = {}
    for o in ovs:
        for pid in (o.get("project_a"), o.get("project_b")):
            u = proj_ids.get(pid)
            if u:
                covered.setdefault(u, set()).add(pid)
    out["coverage"] = {
        u: {"projects": by_util.get(u, 0),
            "in_overlaps": len(ids)}
        for u, ids in covered.items()
    }
    return out


@app.get("/api/raw/{path:path}")
def raw_file(path: str) -> FileResponse:
    """Serve a raw filing (e.g. a downloaded PDF) — provenance links in UI."""
    target = (ROOT / "data" / "raw" / path).resolve()
    if not str(target).startswith(str((ROOT / "data" / "raw").resolve())):
        raise HTTPException(403, "path escapes raw data dir")
    if not target.exists():
        raise HTTPException(404, "not found")
    return FileResponse(target)
