"""CO-GRID backend — FastAPI serving processed GeoJSON/JSON artifacts.

Run:  ./venv/bin/uvicorn src.api.main:app --host 127.0.0.1 --port 8000 --reload
Data: everything under data/processed/ (generated by src/processing/*).
"""
from __future__ import annotations

import csv
import gzip
import io
import json
import os
from functools import lru_cache
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv
from fastapi import FastAPI, Header, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from fastapi.middleware.gzip import GZipMiddleware
from fastapi.responses import FileResponse, Response

load_dotenv()

ROOT = Path(__file__).resolve().parents[2]
PROCESSED = ROOT / "data" / "processed"
RAW = ROOT / "data" / "raw"
EXPORTS = ROOT / "exports"  # agent-generated downloads (gitignored)

# the only artifact types export_data writes — anything else is refused
_EXPORT_MIME = {
    ".csv": "text/csv",
    ".xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    ".html": "text/html",
}

app = FastAPI(title="CO-GRID API", version="0.1.0")
app.add_middleware(
    CORSMiddleware,
    allow_origins=[os.getenv("CORS_ORIGIN", "http://127.0.0.1:3210"), "http://localhost:3210"],
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)
# ~27 MB city scenes -> ~5 MB on the wire; huge win for first paint.
app.add_middleware(GZipMiddleware, minimum_size=20_000)

# AI coordination analyst (OpenAI-compatible backend, key stays server-side)
from src.agent.routes import router as agent_router  # noqa: E402
app.include_router(agent_router)

# Deterministic analysis layer — timeline bands, impact/cost estimates
from src.analysis.routes import router as analysis_router  # noqa: E402
app.include_router(analysis_router)


def _load(name: str) -> dict:
    path = PROCESSED / name
    if not path.exists():
        raise HTTPException(503, f"{name} not generated yet — run the processing pipeline")
    return json.loads(path.read_text())


@lru_cache(maxsize=8)
def _cached(name: str, mtime: float) -> dict:  # noqa: ARG001 — mtime busts cache
    return _load(name)


def _fresh(name: str) -> dict:
    path = PROCESSED / name
    return _cached(name, path.stat().st_mtime if path.exists() else 0.0)


@lru_cache(maxsize=16)
def _gzipped(path_str: str, mtime: float) -> bytes:  # noqa: ARG001 — mtime busts cache
    """gzip-compressed file bytes for the city endpoint — one compress
    pass per artifact version instead of per request (the middleware
    would redo a ~20–50 MB compresslevel=9 pass on every call)."""
    return gzip.compress(Path(path_str).read_bytes())


@lru_cache(maxsize=4)
def _program_rollup(mtime: float) -> dict:  # noqa: ARG001 — mtime busts cache
    """Staging/season rollup for /api/stats — cached on overlaps.json
    mtime; the cluster build is O(records²) so it must not recompute
    per request."""
    from src.analysis.clusters import build_clusters
    from src.analysis.optimize import build_playbook
    ovs = _fresh("overlaps.json").get("overlaps", [])
    cl = build_clusters({"overlaps": ovs}, 40.0)
    pb = build_playbook({"overlaps": ovs}, 40.0, 5)
    seasons = [s for c in pb.get("clusters", []) for s in c.get("seasons", [])]
    return {
        "staging_yards": cl.get("cluster_count", 0),   # estimated yards needed
        "staging_corridors": cl.get("corridor_count", 0),
        "peak_season": max(seasons, key=lambda s: s["site_count"], default=None),
    }


@app.get("/api/health")
def health() -> dict:
    return {"ok": True, "processed": sorted(p.name for p in PROCESSED.glob("*"))}


@app.get("/api/meta")
def meta() -> dict:
    """Artifact freshness — when each processed file was built and its size.
    Lets the UI show 'data generated <ts>' honestly."""
    import datetime as _dt
    files = {}
    for p in sorted(PROCESSED.glob("*")):
        st = p.stat()
        files[p.name] = {
            "bytes": st.st_size,
            "built_utc": _dt.datetime.fromtimestamp(
                st.st_mtime, tz=_dt.timezone.utc).isoformat(timespec="seconds"),
        }
    return {"processed": files,
            "raw_files": sum(1 for p in RAW.glob("**/*") if p.is_file()) if RAW.exists() else 0}


@app.get("/api/projects")
def projects(
    utility: Optional[str] = Query(None),
    zone: Optional[str] = Query(None),
    q: Optional[str] = Query(None, description="substring match on id, name, utility, source"),
) -> dict:
    fc = _fresh("projects.geojson")
    feats = fc.get("features", [])
    if utility:
        feats = [f for f in feats if f["properties"].get("utility") == utility]
    if zone:
        # zones may be missing or null — never default-match the filter
        feats = [f for f in feats
                 if zone in (f["properties"].get("zones") or [])]
    if q:
        needle = q.strip().lower()
        feats = [f for f in feats if needle in json.dumps(
            f.get("properties", {})).lower()]
    return {**fc, "features": feats}


@app.get("/api/basemap")
def basemap(zone: Optional[str] = Query(None)) -> dict:  # noqa: ARG001
    return _fresh("basemap.geojson")


@app.get("/api/city/{scene}")
def city(scene: str, accept_encoding: Optional[str] = Header(None)):
    if scene not in (
        "savannah",
        "augusta",
        "state",
        # metro cores — composited into the statewide view as detail
        "atlanta",
        "columbia",
        "charleston",
        "greenville_sc",
        "columbus_ga",
        "athens",
        "macon",
    ):
        raise HTTPException(404, "unknown scene")
    path = PROCESSED / f"city_{scene}.json"
    if not path.exists():
        raise HTTPException(
            503, f"city_{scene}.json not generated yet — run the processing pipeline")
    # Pre-compressed fast path: serve the cached gzip blob straight from
    # the file bytes — same JSON the dict path would serialize, minus a
    # ~20–50 MB re-encode + re-compress per request. GZipMiddleware sees
    # the Content-Encoding header and passes the body through untouched.
    if accept_encoding and "gzip" in accept_encoding:
        return Response(
            content=_gzipped(str(path), path.stat().st_mtime),
            media_type="application/json",
            headers={"Content-Encoding": "gzip", "Vary": "Accept-Encoding"},
        )
    return _fresh(f"city_{scene}.json")


@app.get("/api/state-bounds")
def state_bounds() -> dict:
    """GA + SC state boundary polygons (WGS84 GeoJSON) — Census Bureau
    2024 500k cartographic boundary set, public domain. Used for the
    state outlines and the flat-map land fill."""
    return _fresh("state_bounds.geojson")


@app.get("/api/regions")
def regions() -> dict:
    """Index of renderable regions/scenes — the contract for statewide tiles.
    Each entry: id, label, lon/lat bounds, center, and which artifacts exist.
    The frontend can offer scene switching/tiles off this list without
    hardcoding geography."""
    from src.processing.projection import SCENES
    out = []
    for scene, label in [
        ("savannah", "Savannah corridor"),
        ("augusta", "Augusta corridor"),
        ("atlanta", "Atlanta core"),
        ("columbia", "Columbia SC core"),
        ("charleston", "Charleston core"),
        ("greenville_sc", "Greenville SC core"),
        ("columbus_ga", "Columbus GA core"),
        ("athens", "Athens core"),
        ("macon", "Macon core"),
    ]:
        p = PROCESSED / f"city_{scene}.json"
        out.append({
            "id": scene,
            "label": label,
            "bounds": list(SCENES[scene]["bbox"]),
            "center": list(SCENES[scene]["center"]),
            "artifact": f"city_{scene}.json",
            "built": p.exists(),
            "size_mb": round(p.stat().st_size / 1e6, 1) if p.exists() else None,
        })
    # Statewide entry — basemap.geojson now covers GA+SC (~15.7k features);
    # the city_<state>.json scene lands separately (tiles, not one payload).
    bm = PROCESSED / "basemap.geojson"
    out.append({
        "id": "state",
        "label": "Georgia + South Carolina (statewide)",
        "bounds": list(SCENES["state"]["bbox"]),
        "center": list(SCENES["state"]["center"]),
        "artifact": "basemap.geojson",
        "built": bm.exists(),
        "size_mb": round(bm.stat().st_size / 1e6, 1) if bm.exists() else None,
        "city_scene": (PROCESSED / "city_state.json").exists(),
        "coverage": "existing grid statewide; planned projects corridor-focused",
    })
    # zone rollup — region tags carried by the data itself (projects.zones
    # and the derived overlap.zone labels) so a picker can scope by region.
    projs = _fresh("projects.geojson").get("features", [])
    ovs = _fresh("overlaps.json").get("overlaps", [])
    zones: dict[str, dict] = {}
    for f in projs:
        for z in f["properties"].get("zones") or []:
            zones.setdefault(z, {"id": z, "projects": 0, "overlaps": 0})
            zones[z]["projects"] += 1
    for o in ovs:
        for z in (o.get("zone") or "").split(" / "):
            if z in zones:
                zones[z]["overlaps"] += 1
    return {"regions": out, "zones": sorted(zones.values(), key=lambda z: -z["overlaps"])}


_OVERLAP_SORTS = {
    "score": lambda r: (-r.get("score", 0)),
    # 0.0 km (touching) is a real distance, not missing — test for None,
    # never `or` (falsy 0.0 used to send all tier-1 records to the end)
    "distance": lambda r: (
        r["min_distance_km"] if r.get("min_distance_km") is not None else 1e9,
        -r.get("score", 0)),
    "distance_desc": lambda r: (
        -(r["min_distance_km"] if r.get("min_distance_km") is not None else -1e9),
        -r.get("score", 0)),
    "year": lambda r: (
        (r.get("shared_window") or {}).get("start") or 9999,
        -r.get("score", 0)),
}


@app.get("/api/overlaps")
def overlaps(
    tier: Optional[int] = Query(None, ge=1, le=4),
    timeline_only: bool = Query(False),
    q: Optional[str] = Query(None, description="substring match on ids, project names, utilities"),
    zone: Optional[str] = Query(None, description="region tag — matches zone labels incl. 'a / b' pairs"),
    state: Optional[str] = Query(None, description="ga | sc — records whose zone touches that state"),
    sort: Optional[str] = Query(None, description="score | distance | distance_desc | year"),
    limit: Optional[int] = Query(None, ge=1, le=500),
    offset: int = Query(0, ge=0, description="skip N rows after filter/sort (paging)"),
    geometry: bool = Query(True, description="false drops zone_geometry polygons"),
    fields: Optional[str] = Query(
        None, description="comma-separated record keys to keep (slim payload)"),
) -> dict:
    data = _fresh("overlaps.json")
    rows = data.get("overlaps", [])
    if tier is not None:
        rows = [r for r in rows if r["tier"] == tier]
    if zone:
        z = zone.strip().lower()
        rows = [r for r in rows if z in (r.get("zone") or "").lower()]
    if state:
        from src.analysis.filters import filter_records as _fr
        try:
            rows = _fr(rows, state=state)
        except ValueError as e:
            raise HTTPException(422, str(e)) from e
    if timeline_only:
        rows = [r for r in rows if r["timeline_overlap"]]
    if q:
        needle = q.strip().lower()
        rows = [r for r in rows if needle in json.dumps({
            "id": r.get("overlap_id"), "a": r.get("project_a"),
            "b": r.get("project_b"), "u": r.get("utilities"),
            "x": r.get("explanation"),
        }).lower()]
    if sort is not None:
        if sort not in _OVERLAP_SORTS:
            raise HTTPException(422, f"unknown sort {sort!r} — use score|distance|distance_desc|year")
        rows = sorted(rows, key=_OVERLAP_SORTS[sort])
    total = len(rows)
    if offset:
        rows = rows[offset:]
    if limit is not None:
        rows = rows[:limit]
    if not geometry:
        rows = [{k: v for k, v in r.items() if k != "zone_geometry"} for r in rows]
    if fields:
        keep = {k.strip() for k in fields.split(",") if k.strip()}
        rows = [{k: r.get(k) for k in keep} for r in rows]
    return {**data, "overlaps": rows, "total": total, "offset": offset}


@app.get("/api/overlaps.csv")
def overlaps_csv(
    utility: Optional[str] = Query(None),
    utilities: Optional[str] = Query(
        None, description="exact pair, comma-separated — e.g. 'DESC,GPC'"),
    tier: Optional[int] = Query(None, ge=1, le=4),
    zone: Optional[str] = Query(None),
    state: Optional[str] = Query(None, description="ga | sc"),
    timeline_only: bool = Query(False),
    adjacent_only: bool = Query(False),
    missing_dates: bool = Query(False),
    sort: Optional[str] = Query(None, description="score | distance | distance_desc | year"),
) -> "Response":
    """Ranked overlaps as flat CSV — teammates/spreadsheets/BI friendly.
    Accepts the same filters as the agent's find_overlaps tool (shared
    filter_records) so agent-emitted csv_export links are faithful."""
    from fastapi.responses import Response
    from src.analysis.filters import filter_records
    from src.processing.projection import scene_for_zone

    rows = _fresh("overlaps.json").get("overlaps", [])
    try:
        rows = filter_records(
            rows, utility=utility, utilities=utilities, tier=tier,
            zone=zone, state=state, timeline_only=timeline_only,
            adjacent_only=adjacent_only, missing_dates=missing_dates)
    except ValueError as e:
        raise HTTPException(422, str(e)) from e
    if sort is not None:
        if sort not in _OVERLAP_SORTS:
            raise HTTPException(422, f"unknown sort {sort!r} — use score|distance|distance_desc|year")
        rows = sorted(rows, key=_OVERLAP_SORTS[sort])
    rows = list(rows)  # overlaps.json is already engine-ordered

    cols = [
        "rank", "overlap_id", "project_a", "project_b", "utilities",
        "tier", "tier_label", "zone", "min_distance_km", "timeline_overlap",
        "timeline_adjacent", "shared_window_start", "shared_window_end",
        "closest_lon", "closest_lat", "score",
        "shared_row_km", "est_savings_low_usd", "est_savings_high_usd",
        "explanation", "map_link",
    ]
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(cols)
    for i, r in enumerate(rows, 1):
        win = r.get("shared_window") or {}
        cp = r.get("closest_point_a") or [None, None]
        cost = r.get("cost") or {}
        w.writerow([
            i, r.get("overlap_id"), r.get("project_a"), r.get("project_b"),
            "|".join(r.get("utilities") or []), r.get("tier"), r.get("tier_label"),
            r.get("zone"), r.get("min_distance_km"), r.get("timeline_overlap"),
            r.get("timeline_adjacent", False),
            win.get("start"), win.get("end"), cp[0], cp[1], r.get("score"),
            cost.get("shared_row_km"), cost.get("est_savings_usd_low"),
            cost.get("est_savings_usd_high"), r.get("explanation"),
            f"/?scene={scene_for_zone(r.get('zone'))}"
            f"&select={r.get('overlap_id')}&panel=0",
        ])
    return Response(
        content=buf.getvalue(),
        media_type="text/csv",
        headers={"Content-Disposition": 'attachment; filename="co-grid-overlaps.csv"'},
    )


@app.get("/api/stats")
def stats() -> dict:
    projs = _fresh("projects.geojson").get("features", [])
    ovs = _fresh("overlaps.json").get("overlaps", [])
    by_util: dict[str, int] = {}
    by_tier: dict[str, int] = {}
    for f in projs:
        u = f["properties"].get("utility", "?")
        by_util[u] = by_util.get(u, 0) + 1
    for o in ovs:
        t = str(o["tier"])
        by_tier[t] = by_tier.get(t, 0) + 1
    out = {
        "projects": len(projs),
        "by_utility": by_util,
        "overlaps": len(ovs),
        "by_tier": by_tier,
        "timeline_matches": sum(1 for o in ovs if o["timeline_overlap"]),
        "timeline_adjacent": sum(1 for o in ovs if o.get("timeline_adjacent")),
    }
    # program-level rollup — staging regions + busiest shared season
    # (cached on overlaps.json mtime — the cluster build is O(n²))
    try:
        mtime = (PROCESSED / "overlaps.json").stat().st_mtime
        out.update(_program_rollup(mtime))
    except Exception:
        out["staging_yards"] = None
        out["staging_corridors"] = None
        out["peak_season"] = None
    # per-utility coverage: filed projects participating in >=1 overlap
    proj_ids = {
        f["properties"].get("project_id"): f["properties"].get("utility", "?")
        for f in projs
    }
    covered: dict[str, set] = {u: set() for u in by_util}
    for o in ovs:
        for pid in (o.get("project_a"), o.get("project_b")):
            u = proj_ids.get(pid)
            if u:
                covered.setdefault(u, set()).add(pid)
    out["coverage"] = {
        u: {"projects": by_util.get(u, 0),
            "in_overlaps": len(ids)}
        for u, ids in covered.items()
    }
    return out


@app.get("/api/exports/{name}")
def export_file(name: str) -> FileResponse:
    """Serve one generated export (the agent's export_data links point
    here). Names are confined to the flat exports/ dir — separators,
    traversal, and non-export extensions are all refused."""
    if "/" in name or "\\" in name or ".." in name:
        raise HTTPException(403, "bad export name")
    ext = Path(name).suffix.lower()
    if ext not in _EXPORT_MIME:
        raise HTTPException(403, "only .csv/.xlsx/.html exports are served")
    target = (EXPORTS / name).resolve()
    if not target.is_relative_to(EXPORTS.resolve()) or not target.is_file():
        raise HTTPException(404, "export not found — it may have been cleaned up")
    return FileResponse(target, media_type=_EXPORT_MIME[ext],
                        filename=name)


@app.get("/api/raw/{path:path}")
def raw_file(path: str) -> FileResponse:
    """Serve a raw filing (e.g. a downloaded PDF) — provenance links in UI."""
    raw_root = (ROOT / "data" / "raw").resolve()
    target = (raw_root / path).resolve()
    if not target.is_relative_to(raw_root):
        raise HTTPException(403, "path escapes raw data dir")
    if not target.exists():
        raise HTTPException(404, "not found")
    return FileResponse(target)
