"""CO-GRID backend — FastAPI serving processed GeoJSON/JSON artifacts.

Run:  ./venv/bin/uvicorn src.api.main:app --host 127.0.0.1 --port 8000 --reload
Data: everything under data/processed/ (generated by src/processing/*).
"""
from __future__ import annotations

import json
import os
from functools import lru_cache
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse

load_dotenv()

ROOT = Path(__file__).resolve().parents[2]
PROCESSED = ROOT / "data" / "processed"

app = FastAPI(title="CO-GRID API", version="0.1.0")
app.add_middleware(
    CORSMiddleware,
    allow_origins=[os.getenv("CORS_ORIGIN", "http://127.0.0.1:3210"), "http://localhost:3210"],
    allow_methods=["GET"],
    allow_headers=["*"],
)


def _load(name: str) -> dict:
    path = PROCESSED / name
    if not path.exists():
        raise HTTPException(503, f"{name} not generated yet — run the processing pipeline")
    return json.loads(path.read_text())


@lru_cache(maxsize=8)
def _cached(name: str, mtime: float) -> dict:  # noqa: ARG001 — mtime busts cache
    return _load(name)


def _fresh(name: str) -> dict:
    path = PROCESSED / name
    return _cached(name, path.stat().st_mtime if path.exists() else 0.0)


@app.get("/api/health")
def health() -> dict:
    return {"ok": True, "processed": sorted(p.name for p in PROCESSED.glob("*"))}


@app.get("/api/projects")
def projects(
    utility: Optional[str] = Query(None),
    zone: Optional[str] = Query(None),
) -> dict:
    fc = _fresh("projects.geojson")
    feats = fc.get("features", [])
    if utility:
        feats = [f for f in feats if f["properties"].get("utility") == utility]
    if zone:
        feats = [f for f in feats if zone in f["properties"].get("zones", [zone])]
    return {**fc, "features": feats}


@app.get("/api/basemap")
def basemap(zone: Optional[str] = Query(None)) -> dict:  # noqa: ARG001
    return _fresh("basemap.geojson")


@app.get("/api/city/{scene}")
def city(scene: str) -> dict:
    if scene not in ("savannah", "augusta"):
        raise HTTPException(404, "unknown scene")
    return _fresh(f"city_{scene}.json")


@app.get("/api/overlaps")
def overlaps(
    tier: Optional[int] = Query(None, ge=1, le=4),
    timeline_only: bool = Query(False),
) -> dict:
    data = _fresh("overlaps.json")
    rows = data.get("overlaps", [])
    if tier is not None:
        rows = [r for r in rows if r["tier"] == tier]
    if timeline_only:
        rows = [r for r in rows if r["timeline_overlap"]]
    return {**data, "overlaps": rows}


@app.get("/api/stats")
def stats() -> dict:
    projs = _fresh("projects.geojson").get("features", [])
    ovs = _fresh("overlaps.json").get("overlaps", [])
    by_util: dict[str, int] = {}
    by_tier: dict[str, int] = {}
    for f in projs:
        u = f["properties"].get("utility", "?")
        by_util[u] = by_util.get(u, 0) + 1
    for o in ovs:
        t = str(o["tier"])
        by_tier[t] = by_tier.get(t, 0) + 1
    return {
        "projects": len(projs),
        "by_utility": by_util,
        "overlaps": len(ovs),
        "by_tier": by_tier,
        "timeline_matches": sum(1 for o in ovs if o["timeline_overlap"]),
    }


@app.get("/api/raw/{path:path}")
def raw_file(path: str) -> FileResponse:
    """Serve a raw filing (e.g. a downloaded PDF) — provenance links in UI."""
    target = (ROOT / "data" / "raw" / path).resolve()
    if not str(target).startswith(str((ROOT / "data" / "raw").resolve())):
        raise HTTPException(403, "path escapes raw data dir")
    if not target.exists():
        raise HTTPException(404, "not found")
    return FileResponse(target)
